source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'MMDrawerController', '~> 0.5.7'